'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Artists', [
      { artistName: "Clean Bandit", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Oliver Heldens", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Joel Corry", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Disciples", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Wynter Gordon", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Loreen", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Rudimental", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Missy Elliot", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Lilly Wood & The Prick", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "The Magician", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Janelle Monae", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Wiley", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Krystal Klear", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Galantis", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Tori Amos", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Sam and the Womp", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Andy C", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Klingande", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Kwabs", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "NONOMO", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "KANT", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Blonde", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "TIEKS", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Lykke Li", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Gabrielle Aplin", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Daft Punk", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Kylie Minogue", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "En Vogue", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "All About She", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Tube & Berger", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Alesha Dixon", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "All Saints", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Tinie Tempah", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Corona", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "JX", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Grace", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "M&S", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "LCD Soundsystem", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "The Tamperer", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Perfecto Allstarz", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Hard-Fi", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Pendulum", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Sagat", createdAt: new Date(), updatedAt: new Date() },
      { artistName: "Little Boots", createdAt: new Date(), updatedAt: new Date() },
      // { artistName: "Krishane" },
      // { artistName: "The Streets" },
      // { artistName: "Prince & The Revolution" },
      // { artistName: "Hysteric Ego" },
      // { artistName: "Ten City" },
      // { artistName: "Billie Ray Martin" },
      // { artistName: "New Order" },
      // { artistName: "Blur" },
      // { artistName: "Jess Glynn" },
      // { artistName: "Crazy Cousinz" },
      // { artistName: "Devolution" },
      // { artistName: "Cece Rogers" },
      // { artistName: "Delilah" },
      // { artistName: "Panteros666" },
      // { artistName: "ColdPlay" },
      // { artistName: "BT" },
      // { artistName: "Ascension" },
      // { artistName: "Tanita Tikaram" },
      // { artistName: "James Hype & Kelli-Leigh" },
      // { artistName: "Timos Maas" },
      // { artistName: "Avicii" },
      // { artistName: "StooShee" },
      // { artistName: "Conor Maynard" },
      // { artistName: "Marina" },
      // { artistName: "Charli XCX" },
      // { artistName: "Trey Songz" },
      // { artistName: "Ten City" },
      // { artistName: "Planet Perfecto" },
      // { artistName: "Kaz James" },
      // { artistName: "William Orbit" },
      // { artistName: "Rae Morris" },
      // { artistName: "Rudimental" },
      // { artistName: "Breach" },
      // { artistName: "Leviticus" },
      // { artistName: "UN-CUT" },
      // { artistName: "Lily Allen" },
      // { artistName: "McLean" },
      // { artistName: "Together" },
      // { artistName: "The Grid" },
      // { artistName: "Opus III" },
      // { artistName: "Deee-Lite" },
    ], {});
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.
      Example:
      */
    return queryInterface.bulkDelete('Artists', null, {});
  }
};
